### ISSUE TITLE
POTENTIAL ALLELECTRON cann't be recognized by CP2K

### ISSUE THREAD

**Issue by tctgi** [pierre-24/cp2k-basis#26]
Dear developers,

I found this issue when I tried to use all-electron potential in CP2K:
![image](https://github.com/pierre-24/cp2k-basis/assets/166786701/6ab7c965-7bea-4ed6-907e-86944c1560a5)

Instead, using ALL would solve the problem.

Best wish,
tctgi

**Comment by pierre-24** [comment]
Interesting. I always though that this was just a label and that you can use any of them (that's how it works for basis sets, at least). I'll look into that :)

**Comment by pierre-24** [comment]
That is fixed in the code. I will deploy that in the live version by today or tomorrow.

**Comment by pierre-24** [comment]
... And that's online:

![image](https://github.com/user-attachments/assets/93650de1-e47a-4725-bc1e-02db515473e8)
